version: "3"

services:
  service1:
    build:
      context: service1
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
  service2:
    build:
      context: service2
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
